name: Show Notes Update
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 18 * * 5' # https://crontab.guru/#40_18_*_*_5
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  show_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: '3.9'
      - name: Capture Versions & Install Requirements
        run: |
         python --version
         git --version
         gh version
      - name: Check for and generate new show notes
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_PLAYLIST_ID: "PLjF7R1fz_OOXBHlu9msoXq2jQN4JpCk8A"
        run: |
          pip install -r requirements.txt
          python tools/yt_playlist_show_notes.py
      - name: Git Add & Commit
        if: ${{ env.NEWFILE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWER: "tannewt"
        run: |
          echo "Config GH User and Email"
          git config user.name "Github Actions Bot"
          git config user.email "<>"
          echo "Create Branch"
          git checkout -b ${{ env.NEWFILE_PATH }}
          echo "Add file to branch"
          git add ${{ env.NEWFILE_PATH }}
          echo "Commit file to branch"
          git commit -m "Show Notes ${{ env.NEWFILE_PATH }}"
          echo "Push branch to GH"
          git push --set-upstream origin ${{ env.NEWFILE_PATH }}
          echo "Create PR"
          gh pr create --reviewer ${{ env.REVIEWER }} --title "Show Notes ${{ env.NEWFILE_PATH }}" --body "Show Notes ${{ env.NEWFILE_PATH }}"
